### PR TITLE
Add UART and SPI display

### PR DESCRIPTION
**Pull request by kmatch98**
This pull request adds options for accepting keyboard input via UART (see variable "inputUART")
and an option for output to a connected SPI display (see variable "displayOutput).

The code for the displayOutput to an SPI display relies on the simpleTerminal library found at:
https://github.com/kmatch98/simpleTerminal

@robert-hh, please let me know if you are interested in merging this into your current version.  In my testing, the code still works with stdin/stdout if you set "inputUART=False" and "displayOutput=False".

You may not have any way of testing this on hardware, but if so I'd appreciate your feedback on whether this works for you.

Things that could be improved:
1. Add the required UART and display inputs (e.g. screen size) as input variables to the pye() function.
2. Add highlight capabilities for the SPI display.

### CODE REVIEW

**Comment by kmatch98** [comment]
I forgot to mention, one thing I couldn't verify was the mouse functionality.

**Comment by kmatch98** [comment]
I'm trying to figure out a plan of attack for merging my "pye_mp.py" changes into the main file "pye.mp" so that your strip.sh can extract the appropriate versions for the different platforms.  

I'd like your guidance on a few items:

1. A good name for the CircuitPython version with added UART and display output. Maybe "io"?

2. I have the code with two flags (Editor.displayOutput and Editor.inputUART) that allows individual selection of the input and output from stdin/stdout to UART/display.  When debugging, I took advantage of being able to switch back and forth between input and output modes.  However, this adds complexity (and lines) to the code, and I'm not sure the best way of handling this.

In the current version, the main variants are linux and MicroPython/CircuitPython and there are only a couple of places where the code is different.  In contrast, I have changes sprinkled throughout, with "if Editor.displayOutput" statements that give the user options to switch between stdout and the display output.  I'm struggling to come up with an easy way of making the code reusable and include these

Option 1: Just put ifdef statements throughout the text to accommodate with all these small changes.
Option 2: Delete the ability to switch back and forth between stdin/stdout and UART/display.  This would allow better code reuse and improve readability of the "pye.py" file, but would require program files with several different input/output "flavors" if someone wants a different combination of inputs/output options.  

3. I'm fairly new to python and object oriented programming, so I have a structural/organizational question.  I moved several functions to the top level (same level as the main pye function), since they should only be executed once (init_display, deinit_display, init_tty, and deinit_tty).  Since I have to setup the display and UART only once, I didn't want to put it in the class _init_ function.  (Or if I did, I would have to create an "already setup?" flag inside the class that seemed clunky.) Somehow my current incarnation doesn't seem like the right way to do it, I'd like your inputs if there is a better way to structure this.

Thanks again for your patience with me on this.  I really appreciate your inputs and I hope I can contribute something back.  Your editor is a great help to me, and I hope these small contributions can help more people take advantage of this editor.

**Comment by robert-hh** [comment]
- Do not take   short name for that variant. Use something like DIRECT_LCD_IO or the like. io is the name of a standard Python module
- Group the specific io functions into one block and do not switch inside of a function. This way, each of these functions stay short, and strip.sh will keep only the code of interest. Like it is done already for wr(), rd(), init(). 
- init_tty() is only called once. You you can put all init code to that place.
- I have the impression that you scroll_up() scroll_down() functions have zero effect. The reason is the mechanism of display_window(). display_window() keeps a shadow copy of the screen content and updates only lines that have been changed. If the screen is scrolled, you have also to change the content of that shadow copy accordingly. That is done e.g. in these lines:
```
            Editor.scrbuf[scrolling:] = Editor.scrbuf[:-scrolling]
            Editor.scrbuf[:scrolling] = [''] * scrolling
```
If you omit that, display_window() will in the worst case redraw the full screen. But then, you could as well replace scroll_up() and scroll_down() by a simple 'pass' statement.
- I would have gone a different way. Instead of rewriting so many functions, I would have made a more complex wr() function and simple control sequences, like:
if the first char is ESC, then take the next byte(s) as function specifiyer. What I could do is to group all screen escape sequences into a list, such that it can be easier replaced for other (Pseudo-)-Terminals.

But looking through your code, you modified so many places, that I would not like to merge that into the code. I could add a branch. But keeping that up-to-date will be difficult too.

**Comment by kmatch98** [comment]
Agreed with you that this is too complex to maintain. If it’s not maintainable, then it won’t do anyone any good.  

Let me review your suggestions and take another approach. 

Thanks for your suggestions and comments.

**Comment by kmatch98** [comment]
I've digested your suggestions and here's my plan:

Send as many responsbilities as reasonable back up into the simpleTerminal class, including:
- Determining which writes go to the status line (several are in "line_edit", one in "display_window")
- Push handling translation of the "special characters" inside the simpleTerminal.write function

Have separate versions of the "small functions" up top (e.g. "wr") special for this flavor: flagged as DIRECT_LCD_IO.

Other items:
Scrolling: Great catch on the scrolling.  Of course, you were right that my code was not doing anything (surprise to me!).  Thanks for the clarification on about how updates are handled in display_window.  I updated the scrolling to fix the bug, and it sped up scrolling slightly.

Thanks again for your help and suggestions.

**Comment by robert-hh** [comment]
Later today I will update the editor with a version, that puts all terminal control strings into a single list, similar to the key codes. That makes it easier to change them.

**Comment by robert-hh** [comment]
I have updated pye.py by placing all terminal control codes into a tuple called TERMCAP. Binding that is controlled by a #ifdef VT100 and a variable called termcap_vt100. If a certain function is not supported, just use an empty string at that place. The strings for terminal setting and status line contain item names. That allows changing the order or not showing items. The latter is interesting for the status line.

**Comment by kmatch98** [comment]
Last night I increased the workload on my simpleTerminal class by adding a wrapper “editorTerminal” class that holds both the status line and the main text window (which I treat as two separate terminals so I can make the status highlighted). This new class intercepts any writes to the bottom status row (row=Editor.height) and diverts the text writing to the appropriate terminal. This will eliminate several of the changes that are currently sprinkled through the code.  

In looking at your description of your updates I think your changes will make life easier. I’ll start from your latest revision and see if I can insert my updates cleanly in there with the #ifdef. 

I’m still working to understand why my code hangs whenever I open a second file and then close it. I know it’s related to the init sequence for my class.  I’m working to wrap my brain around the static method flag to understand how (and why) this works.  Clearly I broke this with my additions and it’s now left for me to figure out what I broke, something conceptual that I need to learn. 

I also appreciate your idea of having options for the status line text. With a small display, that will allow to select how much information to include.

Thanks for the updates.

**Comment by robert-hh** [comment]
It is hard to tell what you actually have changed with respect to the first commit. Better close this PR and start over with a fresh new one.

**Comment by kmatch98** [comment]
Yep, will close and restart, still learning how to operate with GitHub most effectively....

**Pull request closed without merging**
