### PR TITLE
User guide

### PR DESCRIPTION
**Pull request by DG12**
step by step install and usage.

less technical.

technical notes at the end.
and
"See Pyboard_Editor.doc"

### CODE REVIEW

**Comment by DG12** [comment]
Have you had a chance to review  this userGuide?

**Comment by robert-hh** [comment]
No. Actually I did not notice the UserGuide yet. A few comments:
- the Del key is not shown properly, when I open the HTML file in chrome
- ^u is an alternative to BackTab. So BackTab should be mentioned
- ^R is shown as Capital, normally you use lowercase letters.
- Home has a similar toggle behavior as End
- Start-Selection / End-Selection can be used by ^Space or ^L in the same way. 

- Undo size default: On any Micro Board (not only PyBoard/WiPy) 50, PC-based: 500
- There is a Linux executable called pye, which can be called directly from the command line. The pye source bundle for Linux is pye_ux.py. pye is just pye_ux.py with a shebang line and the -x flag set.
- Somehow the document is shown twice in the file.

**Comment by DG12** [comment]
Your observations and suggestions: 
1. Char under (before)the cursor addded Del
2. ^u centered,  BackTab added ( I had wanted mention only one to keep it simple and since Mac does not have BackTab ...)
3. backspace -> Backspace
4. ^R -> ^r
5. Home has a similar toggle behavior as End
5. all keystrokes (TH tag) in font-famliiy:monospace
6. alt-left alt-right => esc &larr; / esc &rarr;
7. End selecting..   ^L (uppercase since ^l is difficult to distinguish)
8. Top/Bottom Home End
9. micro board undo default 50, pc 500
10. removed updated time from status line
11. There is a Linux executable called pye, ... mentioned
12. under terminal emulators, added Mac OS terminal
13. removed planned additional features.
14. changed top button to keys
15. removed "not micropython" from PC section
16. added PC heading, The PC version...
17. removed: The largest suitable file size...
18. Files up to about 13kb on ESP8266 and 68kb characters on PyBoard should be safe to edit.
                      ????                ????
19 added redraw and undo
a few other little tweaks.


A.  WHICH ..." related discussion in the MicroPython Forum.  "
B. Please clarify: "compiled byte code "


Let me know if you would like additional changes.

**Comment by DG12** [comment]
PS 
5 "Home has a similar toggle behavior as End "
I don't understand what you mean. pressing [HOME] twice does not jump to top and back to bottom.

**Comment by robert-hh** [comment]
Pushing Home toggles between the start of a line and start of text on a line.
Ctrl-Home gets to the start of the file, Ctr-End to the end of the file.

**Comment by DG12** [comment]
oops , user misunderstanding. Thanks for the prompt reply

**Comment by robert-hh** [comment]
A few comments:
- Backtab deletes Spaces, but is mentioned in the insert section as well. 
- When text is selected, BackTab dedents.
- Find and the find part of replace supports regular expressions.
- You cannot start the PC version with python3 pye.py [args] You have to use either just
  pye [args]
  or
  python3 pye_ux.py [args]
. the available RAM on ESP8266 is too small to run pye from a file. It has to be packed with the firmware into the flash image.

**Comment by DG12** [comment]
1. backtab in insert section removed.
2. UN-indent one or more lines with ^u. or [backtab] 
3. find regular expression, explain replace
4. starting PC version corrected
5. alt arro move blocks

6. save cannot always be performed with control-s. ( aka X-OFF, ) so I changed its keystrokes tp esc s

**Comment by DG12** [comment]
Is this correct?  "Files up to about 13kb on ESP8266"
I thought it was better to use  size rather than lines since lines vary so much in length.

**Pull request merged**
