### PR TITLE
Add DIRECT_LCD_IO and uart_input

### PR DESCRIPTION
**Pull request by kmatch98**
From your latest revision, I merged my edits into your file.  This relies on an updated class (editorTerminal and simpleTerminal) that now handles many of the special functions.  I think it simplifies this pull request from the previous attempt.

I'm unsure how to arrange the #ifdef statements for these new modes.  If this latest structure is more amenable to you, please provide suggestions on how I can best include the desired #ifdef statements.

**DIRECT_LCD_IO** - Provides output to an external display
optional flag **uart_input** - Allows input from UART

Relies on classes **editorTerminal** and **simpleTerminal** from:
[https://github.com/kmatch98/simpleTerminal](https://github.com/kmatch98/simpleTerminal)

### CODE REVIEW

**Comment by robert-hh** [comment]
Thanks. You have committed all  files in the repository. I assume that thsi was not intended. I'll take just the essential ones from that set and work with these. Assuming it to be pye.py and strip.sh.

Note: You might have a look on this script, https://github.com/robert-hh/SSD1963-TFT-Library-for-PyBoard/blob/master/vt100.py, which I made as an example for using the TFT driver. It emulates a VT100 console.

**Comment by robert-hh** [comment]
Looking through your code you should understand, that after preprocessing in strip.sh with
-D DIRECT_LCD_IO, but without -D VT100, every code between #ifdef VT100 and the matching #endif is removed from the file. So code common for all environment must be outside such an #ifdef/#endif clause, and in these clauses there must be additional Python if ... blocks, in case that the full file is executed. Python ignores the #ifdef/#endif lines as being comments.

**Comment by kmatch98** [comment]
My apologies for all the commits. I’m still working tO better understand how to use github. My daughter is home from college and she’s helping me there too. 

I’m trying to get my computer setup to run your strip shell script so I can understand how to properly insert the #ifdef statements. Thanks again for your patience with me  on this.  Give me a day or two to experiment and then I hope to update the code for this pull request.

**Comment by robert-hh** [comment]
No nedd to apologize. I am fighting with git too, especially when it comes to interaction with github, PR's and merges.
I had a look at your Terminal class for the LCD, and it looks good. You implemented the detection of VT100 sequences. That's fine, and makes my changes to collect all control strings in a single place obsolete. I will make a further change to that, including the warning msg. about leaving with changed content. That allows to concentrate port-specific code in a single place. As a side note: you can also change the KEY_MAP in the fly for instance by writing in your init code:

`Editor.KEYMAP['\x08'] = KEY_BACKSPACE`

Later today I will try to apply #ifdef to your code. I am not yet sure myself what is the best approach.

**Comment by kmatch98** [comment]
Thanks for the input on a way to override the key mapping in the specific location where needed for the special UART input version. Now that you say it, it is really obvious. 

I didn’t have time to review the #ifdef statements and will be tied up for the next day or so on some construction here at the house so I don’t expect to make any suggestions for a couple of days. I was thinking that the Display and UART code can go together. The UART code doesn’t add very many lines so it may be just as easy to group them and the user can then set the UART flag as they wish. I found this really handy when debugging everything so I could understand which problems were a UART problem and which was a problem with the rest of the code. I’m interested to hear your ideas. 

Also, the editor made an appearance on the Adafruit show channel this week. I think the editor running on a standalone “computer” made a positive impression.

[video showing the pye editor](https://youtu.be/1XwYP0y4Prg?t=2112)

**Comment by robert-hh** [comment]
That's a good video.
Thinking about the code grouping, it does not need to differ between VT100 or other codes, since you implemented the VT100 codes in your terminal software. It would require the switch between DIRECT_LCD_IO and CONSOLE_IO. The latter would be the standard method using sys.stdin and sys.stdout. The problem there is, that different from the other switches for e.g. Linux and Micropython, there is not simple programmatic way to tell.  I have still the aim, that the full file would run in any of the supported environments. The only way I have now is trying to import the files for direct_lcd_io. If it succeeds, direct_lcd_io is used, otherwise console_io.
I changed my files on github again, using a shorter status line if required.

**Comment by robert-hh** [comment]
I have uploaded a branch called lcd_io to the repository. I added your code into pye.py and made strip.sh to create a version called pye_lcd.py, which only contains the code for direct_lcd_io. I kept the separate functions for goto, etc.., but since you implemented the VT100 parsing, this may not be required. Since I have no suitable display here, I could not test it.
To be honest: I have quite a few displays here, but not the one you used and not the CircuitPython board you use. Did you mention the model of the board?

**Comment by kmatch98** [comment]
I am using an Adafruit ItsyBitsy M4, but I suspect almost any board will work If it runs CircuitPython and has enough memory. If you have a different kind of display then you will need to edit the display library that is used and the pin wiring connections for the SPI. 

It sounds like you made some good progress. I’m tied up today away from home.  I’ll check it out tonight.

**Comment by kmatch98** [comment]
robert-hh, the code in the lcd-io branch looks great!  I ran the base "pye.py" version and it worked for me.  I see where you put the `Editor.KEYMAP['\x08'] = KEY_BACKSPACE` in the init.tty function, and it works right (and is less confusing that where I originally put it).  

Tomorrow I'll try running your shell script and see if I can get the reduced-sized version to work for me.  Thanks again for the help and for all your patience.

**Comment by robert-hh** [comment]
I forgot to add the stripped-down file pye_lcd.py to the repository. Now it is there.

**Comment by kmatch98** [comment]
I verified the pye_lcd stripped down version, it works great on my configuration.  Thanks for your help on this.

**Pull request closed without merging**
