### PR TITLE
h phor pye version 2.72 file online help .81.

### PR DESCRIPTION
**Pull request by DG12**
Organized geographically, that is, commands that reference the top of the file are at the top of the help.

Use ^o h  to open this help file In another window, switch windows with ^w. When help is needed just ^w again.

No source code changes are necessary and the memory it requires is optional, that is, if you don't need it don't open it.
If you want different or additional notes just edit the file h.

### CODE REVIEW

**Comment by DG12** [comment]
oops a couple more changes

**Comment by robert-hh** [comment]
Take your time. You do not have to close a PR to add changes. Just push another commit, and it will be added to the PR.

**Comment by DG12** [comment]
GitHub won't accept a file without an extension so, gunzip h.gz to h before transferring it to the target board.

@robert-hh  how wide a window do YOU use ?

@robert-hh I didn't understand you comment regarding ^v in  "line edit mode" ?

Watch for version .9 after your comments.
[h.gz](https://github.com/robert-hh/Micropython-Editor/files/8826174/h.gz)

**Comment by robert-hh** [comment]
> @robert-hh how wide a window do YOU use ?

100 characters as default.
 > @robert-hh I didn't understand you comment regarding ^v in "line edit mode" ?

If the cursor is at a certain word in the text window, and you open a line dialogue with e.g. Ctrl-O or Ctr-F, pushing there Ctrl-V copies the word into the command line.

**Comment by robert-hh** [comment]
Ctrl-L also starts the select mode, beecause not all terminal emulators support Ctr-Space. With Linux terminals, Alt-Character is an alternative to Ctr-Charater. Since Alt-Character sends the sequence Esc-Character, you can send that as well with any Terminal emulator.

**Comment by DG12** [comment]
Do all terminal emulators (you've checked) support  ^l (ell)

on first line of  h   " ^ is control or esc "

What terminal emulator do you use?  linux, msWindows, Mac ?

**Comment by robert-hh** [comment]
Yes, all Terminal emulators support Ctrl-L. But I prefer as well using Ctrl-Space or the Shift-Cursor keys. As Terminal emulator I use :
Linux: picocom, and tio in rare cases.
OS-X: picocom, and screen in rare cases
Windows: Putty or TeraTerm
My preferred environment is Linux, using Windows or OS-X only for cross-checks.

**Comment by robert-hh** [comment]
It is not ^Up etc. that moves lines or characters, it's Alt-Up etc.

**Comment by robert-hh** [comment]
Thanks. I added that file as it is now. Please keep an eye on that file should the editor ever change. I will not update it.

**Pull request merged**
